esphome:
  name: smart-plug-4
  friendly_name: Smart Plug 4

packages:
  device_base: !include Common/smart-plug.base.yaml
  connection: !include Common/connection.base.yaml

substitutions:
  static_ip: 192.168.0.18
  reboot_timeout: 15min