esphome:
  name: smart-plug-1
  friendly_name: Smart Plug 1

packages:
  device_base: !include Common/smart-plug.base.yaml
  connection: !include Common/connection.base.yaml

substitutions:
  static_ip: 192.168.0.96
  reboot_timeout: 15min