esphome:
  name: kitchen-motion-sensor-2
  friendly_name: Kitchen Motion Sensor 2
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: "esp32-c3-devkitm-1"
  variant: "ESP32C3"
  framework:
    type: "esp-idf"
    version: "recommended"

logger:
    level: WARN

packages:
  presence: !include Common/ld2410.base.yaml
  connection: !include Common/connection.base.yaml

substitutions:
  tx_pin: GPIO21
  rx_pin: GPIO20
  static_ip: 192.168.0.111
  reboot_timeout: 1min

# servo:
#   - id: servo_motor
#     output: pwm_output

# # Example output platform
# # On ESP32, use ledc output
# output:
#   - platform: ledc
#     id: pwm_output
#     pin: GPIO4
#     frequency: 50 Hz

# number:
#   - platform: template
#     name: Servo Control
#     min_value: -100
#     initial_value: 0
#     max_value: 100
#     step: 1
#     optimistic: true
#     set_action:
#       then:
#         - servo.write:
#             id: servo_motor
#             level: !lambda 'return x / 100.0;'