esphome:
  name: kitchen-motion-sensor
  friendly_name: Kitchen Motion Sensor

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    #version: 5.4.1
    version: recommended

logger:
  level: WARN
  baud_rate: 0

packages:
  presence: !include Common/ld2410.base.yaml
  connection: !include Common/connection.base.yaml
  ondevice-led: !include Common/ondevice-led.base.yaml

substitutions:
  tx_pin: RX
  rx_pin: TX
  static_ip: 192.168.0.195
  reboot_timeout: 1min