esphome:
  name: smart-plug-2
  friendly_name: Smart Plug 2

packages:
  device_base: !include Common/smart-plug.base.yaml
  connection: !include Common/connection.base.yaml

substitutions:
  static_ip: 192.168.0.135
  reboot_timeout: 15min